### ISSUE TITLE
Core : MV* 구조잡기

### ISSUE THREAD

**Issue by CurlyBat** [woowa-techcamp-2021/cashbook-9#1]
## 개요 
Model, View 사이의 의존성을 낮게 하기 위한 장치를 적용하기위해 MV*구조를 잡습니다.

## 소요 시간 
4h

## 진행 사항 

- [ ] 좋은 구조를 찾기 위한 학습
- [ ] 구조 적용

## 선행되어야 하는 이슈 

없음

**Comment by hseoy** [comment]
실제 소요 시간 : 3h 50m
