### ISSUE TITLE
달력 : 달력 페이지 서버와 연동

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-9#106]
## 개요 

달력 페이지에서 서버의 데이터를 받아와 달력에 정보를 표시합니다.

## 소요 시간 

1h

## 진행 사항 

- [ ] paymentHistory 모델에 값을 받아오기
- [ ] 달력에 표시

## 선행되어야 하는 이슈 

없음

**Comment by CurlyBat** [comment]
실제 소요 시간 : 30m
