### ISSUE TITLE
내역 표시 : 카테고리 태그 컴포넌트 구현

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-9#14]
## 개요 

<img width="252" alt="스크린샷 2021-07-26 오후 9 30 06" src="https://user-images.githubusercontent.com/75124422/126988852-38ad9294-0a9e-48d2-bf05-c553983cffc4.png">

_카테고리 태그 디자인 시안_ 과 같이 카테고리 태그 컴포넌트를 구현합니다.

## 소요 시간 

40m

## 진행 사항 

- [ ] 마크업 및 스타일링 작성

## 선행되어야 하는 이슈 

없음

**Comment by CurlyBat** [comment]
실제 소요 시간 : 40m
