### ISSUE TITLE
통계 : 원 그래프 구현

### ISSUE THREAD

**Issue by CurlyBat** [woowa-techcamp-2021/cashbook-9#17]
## 개요 

![image](https://user-images.githubusercontent.com/82671736/126989179-3c600d45-4f9e-4e7c-a341-faa7d6747ca7.png)
_원 그래프 이미지_
위와 같이 값을 받아 원 그래프를 그리는 모듈을 구현합니다. 해당 모듈을 사용해서 원 그래프 컴포넌트를 구현합니다.

## 소요 시간 

1d

## 진행 사항 

- [x] 원 모양 마크업, 스타일링
- [x] 정해진 %만큼 구간을 나누기
- [x] _추가사항_ : 애니메이션으로 그래프를 표현
- [x] _추가사항_ : 마우스 hover 시 label 표시
- [x] 해당 모듈을 사용한 원 그래프 컴포넌트 구현

## 선행되어야 하는 이슈 

없음

**Comment by hseoy** [comment]
@CurlyBat 이거는 원래 다음 주에 진행하기로 한 거였는 데, 오늘 쉬면서 refresh도 할 겸 그냥 살펴볼 예정입니당~ㅎㅎ

**Comment by hseoy** [comment]
실제 소요 시간 : 9h 30m

위 링크의 코드펜 코드를 참고해서 코드를 작성했는 데 'jquery 기반 & 이해하기 어려운 구조의 코드' 라서 해당 부분의 코드를 이해하는 데 어려움이 있었고 jquery로 된 부분을 vanilla로 작성하기 위한 변경도 해야 했다. 또한 현재 프로젝트의 구조에서 잘 사용할 수 있도록 모듈을 converting해야 했는데 이 부분에 대해서도 고민이 많아서 시간이 오래 걸렸다.
