### ISSUE TITLE
달력 : 월 컴포넌트 구현

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-9#22]
## 개요 

<img width="632" alt="스크린샷 2021-07-26 오후 9 44 02" src="https://user-images.githubusercontent.com/75124422/126990688-915a830a-f183-4fa2-be29-2980a5466401.png">

_달력 디자인 시안_ 과 같이 컴포넌트를 구현합니다.

## 소요 시간 

2h 40m

## 진행 사항 

- [ ] 마크업 및 스타일링 작성
- [ ] 오늘 날짜는 회색으로 표시
- [ ] 매달 달라지는 일수 계산 및 반영

## 선행되어야 하는 이슈 

#24

**Comment by CurlyBat** [comment]
실제 소요 시간 : 5h

일 컴포넌트 설계에 문제가 있었고, 뷰에서 사용할 수 있는 적합한 구조를 생각하다보니 시간이 오래 걸렸습니다.
