### ISSUE TITLE
Header : Header UI 구현

### ISSUE THREAD

**Issue by CurlyBat** [woowa-techcamp-2021/cashbook-9#4]
## 개요 

![image](https://user-images.githubusercontent.com/82671736/126981252-85c915cb-0c8d-4585-b0b3-81a0096f3c1b.png)
_헤더 이미지_

## 소요 시간 

1h 40m

## 진행 사항 

- [x] 헤더 마크업, 스타일링
- [x] 제어하는 메서드 추가

## 선행되어야 하는 이슈 

- #3

**Comment by hseoy** [comment]
실제 소요 시간 : 2h 10m
