### ISSUE TITLE
내역 입력 : 드랍다운 컴포넌트 구현

### ISSUE THREAD

**Issue by CurlyBat** [woowa-techcamp-2021/cashbook-9#5]
## 개요 

![image](https://user-images.githubusercontent.com/82671736/126985381-e8fa3e2b-56dd-42f1-93a8-58291acbe1bf.png)
_드랍다운 컴포넌트 이미지_
분류 버튼 클릭 시 선택할 수 있게 드롭다운이 생성되어야 합니다.

## 소요 시간 
1h 20m

## 진행 사항 

- [x] 마크업, 스타일링
- [x] hover시 background-color 변경
- [x] 선택된 값을 핸들러에 전달, 등의 이벤트 처리

## 선행되어야 하는 이슈 

없음

**Comment by hseoy** [comment]
실제 소요시간 : 2h
