### ISSUE TITLE
PR 리뷰: 다녀갑니다~

### ISSUE THREAD

**Issue by HobinLee** [woowa-techcamp-2021/cashbook-9#56]
[리뷰 링크](https://github.com/woowa-techcamp-2021/cashbook-9/pull/25#pullrequestreview-718730670)입니다

다음에 시간이 더 많이 있다면 자세히 보고싶어요 ㅠ_ㅠ 역시는 역시다... 9팀 짱입니다 많이 배워갑니다...!

**Comment by kowoohyuk** [comment]
깊게 읽고 나서 리뷰를 남기고 싶었는데 너무 아쉽습니다...  
제가 보기에는 너무 좋은 코드라 사소한 부분에 대한 얘기나 감탄에 대한 리뷰였던 거 같네요! 😭 

[리뷰 링크 1](https://github.com/woowa-techcamp-2021/cashbook-9/pull/55/files#r679655868)

[리뷰 링크 2](https://github.com/woowa-techcamp-2021/cashbook-9/pull/55/files#r679656879)

[리뷰 링크 3](https://github.com/woowa-techcamp-2021/cashbook-9/pull/54#pullrequestreview-718730704)

[리뷰 링크 4](https://github.com/woowa-techcamp-2021/cashbook-9/pull/52#issuecomment-889638981)

[리뷰 링크 5](https://github.com/woowa-techcamp-2021/cashbook-9/pull/51/files#r679658776)

**Comment by hseoy** [comment]
리뷰 감사합니다 ㅠㅠㅠ, 신경쓰지 못한 부분에 대한 리뷰가 정말 좋은 것 같아요~ ㅎㅎ
