### ISSUE TITLE
내역 : 체크박스 컴포넌트 구현

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-9#6]
## 개요 

![image](https://user-images.githubusercontent.com/82671736/127449525-83bb6304-7b4f-4429-b656-374ec571541d.png)

_체크박스 UI 디자인시안_ 과 같이 UI 컴포넌트를 작성합니다.

## 소요 시간 

1h

## 진행 사항 

- [ ] 컴포넌트 마크업/스타일링 작성
- [ ] 이벤트 핸들러 추가

## 선행되어야 하는 이슈 

없음

**Comment by CurlyBat** [comment]
실제 소요 시간 : 1h 40m

어떤 메소드를 만들어놔야 다음에 수정하지않고 쭉 사용할 수 있을지에 대한 고민이 길었습니다
