### ISSUE TITLE
API : API 문서 작성

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-9#68]
## 개요 

API 형식에 대해서 문서로 작성합니다.

## 소요 시간 

2h

## 진행 사항 

- [ ] API 문서 작성

## 선행되어야 하는 이슈 

없음

**Comment by CurlyBat** [comment]
실제 소요 시간 : 1h

페어로 작업 

[API 명세 링크](https://github.com/woowa-techcamp-2021/cashbook-9/wiki/API-%EB%AA%85%EC%84%B8)
