### ISSUE TITLE
데이터베이스 : Node.js 와 데이터베이스 연동

### ISSUE THREAD

**Issue by CurlyBat** [woowa-techcamp-2021/cashbook-9#69]
## 개요 

서버와 데이터베이스를 연동하면서 ORM을 사용합니다.

## 소요 시간 

2h

## 진행 사항 

- [ ] ORM을 통해 데이터베이스에 접근

## 선행되어야 하는 이슈 

없음

**Comment by CurlyBat** [comment]
Sequelize 대신 typeorm 사용

**Comment by hseoy** [comment]
실제 소요 시간 : 4h

원래 사용하려던 Sequelize가 아니라 TypeORM과 TypeDI를 사용하기로 결정하면서 그 패키지를 학습하는 데 시간이 많이 걸렸다.
