### ISSUE TITLE
내역 입력 : 드랍다운 컴포넌트에 삭제 가능한 것도 추가할 수 있도록 기능 추가

### ISSUE THREAD

**Issue by CurlyBat** [woowa-techcamp-2021/cashbook-9#7]
## 개요 
![image](https://user-images.githubusercontent.com/82671736/126987026-e8f8f45b-2309-4c3b-9010-69c7341a86eb.png)
_요소가 삭제 가능한 드랍다운 컴포넌트 이미지_
결제수단 버튼 클릭 시 선택할 수 있게 드롭다운이 생성되어야 합니다.
## 소요 시간 
1h 20m
## 진행 사항 

- [ ] 드랍다운 컴포넌트를 삭제가능한 것도 추가할 수 있도록 수정

## 선행되어야 하는 이슈 

- #5

**Comment by hseoy** [comment]
실제 소요 시간 : 30m
