### ISSUE TITLE
내역 입력 : 결제수단 추가 및 삭제 시 불러올 모달 구현

### ISSUE THREAD

**Issue by CurlyBat** [woowa-techcamp-2021/cashbook-9#8]
## 개요 

![image](https://user-images.githubusercontent.com/82671736/126987687-2c870c4e-ef6f-49de-b4bc-d7c2f5a5ff57.png)
_모달 이미지_
결제수단 추가 또는 삭제 시 적합한 모달이 띄워져야 합니다.
모달 내에서 한 작업들이 적용되어야 합니다.

## 소요 시간 

1h 20m

## 진행 사항 

- [x] 모달 마크업, 스타일링
- [x] open, close 등의 제어 메서드 추가
- [x] 배경 클릭 시 close

## 선행되어야 하는 이슈 

없음

**Comment by hseoy** [comment]
실제 소요 시간 : 1h 20m
