### ISSUE TITLE
내역 : 전체 내역 확인 UI 구현

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-9#9]
## 개요 

<img width="844" alt="스크린샷 2021-07-26 오후 9 21 00" src="https://user-images.githubusercontent.com/75124422/126987790-2e52ae6c-73b1-4807-8b80-a8fbf4307019.png">

_전체 내역 UI 디자인 시안_ 과 같이 전체 내역 개수를 확인하고 체크박스로 수입/지출을 토글하는 UI를 구현합니다.

## 소요 시간 

1h 40m

## 진행 사항 

- [ ] 전체 내역 확인 UI 마크업/스타일링 작성
- [ ] 수입/지출 토글 이벤트 핸들러 추가

## 선행되어야 하는 이슈 

- #6

**Comment by CurlyBat** [comment]
실제 소요 시간 : 1h 30m
