### ISSUE TITLE
버그 : 페이지 이동 시 `Cannot read property 'removeChild' of null` 오류 발생

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-9#90]
## 개요 

메인 페이지 구현 중 메인페이지에서 달력 페이지로 이동했을 때 아래와 같은 오류가 발생하는 것을 발견했습니다.

<img width="945" alt="스크린샷 2021-08-04 오후 10 49 30" src="https://user-images.githubusercontent.com/75124422/128192759-6ac75e0c-bccf-49e3-b9ec-75d723d89a4f.png">

## 소요 시간 

작업하실 때 적어주세요!

## 진행 사항 

- [ ] 직접 적어주세요!

## 선행되어야 하는 이슈 

없음

**Comment by hseoy** [comment]
넵! 알겠습니다~

**Comment by CurlyBat** [comment]
10m
