### ISSUE TITLE
서버연동 : 메인, 달력, 통계에서 접근가능한 api 만들기

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/cashbook-9#94]
## 개요 

서버 요청 함수들을 만들고 해당 함수들을 통해서 모델 업데이트/초기 데이터 가져오기/데이터 추가/삭제 등을 구현합니다.

## 소요 시간 

1h

## 진행 사항 

- [ ] fetch 요청하는 함수 만들기

## 선행되어야 하는 이슈 

- #89 
- #87 
- #85

**Comment by CurlyBat** [comment]
실제 소요 시간 : 40m
